version: '3.8'

services:
  # HTTPS Proxy với Authentication (Cấu hình chính)
  simple-proxy-https:
    build: .
    image: simple-proxy:v1.0.0
    container_name: simple-proxy-https
    ports:
      - "8443:8443"  # HTTPS proxy port
    volumes:
      - ./certs:/certs:ro  # Mount certificates đã tạo
    command: [
      "-protocol", "https",
      "-port", "8443",
      "-cert", "/certs/server.crt",
      "-key", "/certs/server.key", 
      "-basic-auth", "admin:password123",
      "-bind", "0.0.0.0",
      "-timeout", "30",
      "-log-auth",
      "-log-headers"
    ]
    restart: unless-stopped

  # HTTP Proxy với Authentication (Backup option)
  simple-proxy-http:
    build: .
    image: simple-proxy:v1.0.0
    container_name: simple-proxy-http
    profiles: ["http"]  # Start with --profile http
    ports:
      - "3128:3128"
    command: [
      "-port", "3128",
      "-basic-auth", "admin:password123",
      "-bind", "0.0.0.0",
      "-timeout", "30",
      "-log-auth",
      "-log-headers"
    ]
    restart: unless-stopped

  # Simple HTTP Proxy (No auth)
  simple-proxy-simple:
    build: .
    image: simple-proxy:v1.0.0
    container_name: simple-proxy-simple
    profiles: ["simple"]  # Start with --profile simple
    ports:
      - "8888:8888"
    command: [
      "-port", "8888",
      "-bind", "0.0.0.0"
    ]
    restart: unless-stopped